name: Run Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch: #
  pull_request:
    branches: [ main ]
  #schedule:
    #- cron: '12 1 * * *'  # ~3:12 AM German Time
    #- cron: '42 1 * * *'  # ~3:42 AM German Time
    #- cron: '18 2 * * *'  # ~4:18 AM German Time
    #- cron: '48 2 * * *'  # ~4:48 AM German Time
    #- cron: '22 3 * * *'  # ~5:22 AM German Time

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers  
        run:  npx playwright install chromium

      - name: Run tests
        run: npm run test
      
      # Add this step right after your testing step
      - name: Upload Test Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Ensures this runs even if the previous step failed
        with:
          name: playwright-screenshots # You can name this whatever you like
          path: test-results/**/*.png
